"""Tabla pesos actualizada

Revision ID: 06c4b0e6eba2
Revises: 79f58e525e2e
Create Date: 2025-06-04 11:36:58.428546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c4b0e6eba2'
down_revision = '79f58e525e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peso_registro', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')  # <-- Elimina o comenta esta línea
        batch_op.drop_column('turno')
        batch_op.drop_column('nombre')
        batch_op.drop_column('control_promedio')
        batch_op.drop_column('peso_fijado')
        batch_op.drop_column('sabor_id')
        batch_op.drop_column('compensacion')
        batch_op.drop_column('limite_superior')
        batch_op.drop_column('intervalo_auto_cero')
        batch_op.drop_column('numero_estable')
        batch_op.drop_column('maquina')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peso_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maquina', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_estable', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('intervalo_auto_cero', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('limite_superior', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('compensacion', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sabor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('peso_fijado', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('control_promedio', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.VARCHAR(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'flavor', ['sabor_id'], ['id'])

    # ### end Alembic commands ###
