"""Agrega campo nombre a DMEExercise

Revision ID: 5921b0339fed
Revises: 15dc558abc73
Create Date: 2025-05-29 21:02:28.957471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5921b0339fed'
down_revision = '15dc558abc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dme_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dme_exercise', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
