"""Campo de Linea y nombre en tabla pesos

Revision ID: 79f58e525e2e
Revises: c7494a2d9276
Create Date: 2025-06-04 10:21:56.360978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f58e525e2e'
down_revision = 'c7494a2d9276'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('peso_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('linea_id', sa.Integer(), nullable=False))
        batch_op.alter_column('sabor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_peso_registro_linea_id',  # Nombre explícito
            'line',
            ['linea_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peso_registro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sabor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('linea_id')
        batch_op.drop_column('nombre')

    op.create_table('_alembic_tmp_peso_registro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('sabor_id', sa.INTEGER(), nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=100), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.Column('maquina', sa.VARCHAR(length=50), nullable=True),
    sa.Column('turno', sa.VARCHAR(length=10), nullable=True),
    sa.Column('peso_fijado', sa.FLOAT(), nullable=True),
    sa.Column('limite_superior', sa.FLOAT(), nullable=True),
    sa.Column('control_promedio', sa.VARCHAR(length=10), nullable=True),
    sa.Column('compensacion', sa.FLOAT(), nullable=True),
    sa.Column('intervalo_auto_cero', sa.INTEGER(), nullable=True),
    sa.Column('numero_estable', sa.INTEGER(), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=150), nullable=True),
    sa.Column('linea_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['linea_id'], ['line.id'], name=op.f('fk_peso_registro_linea_id')),
    sa.ForeignKeyConstraint(['sabor_id'], ['flavor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
