"""Tabla pesos v3

Revision ID: c7494a2d9276
Revises: 5921b0339fed
Create Date: 2025-06-03 18:22:07.798717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7494a2d9276'
down_revision = '5921b0339fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peso_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maquina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('peso_fijado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('limite_superior', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('control_promedio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('compensacion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('intervalo_auto_cero', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_estable', sa.Integer(), nullable=True))
        batch_op.drop_column('pesos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peso_registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesos', sa.INTEGER(), nullable=False))
        batch_op.drop_column('numero_estable')
        batch_op.drop_column('intervalo_auto_cero')
        batch_op.drop_column('compensacion')
        batch_op.drop_column('control_promedio')
        batch_op.drop_column('limite_superior')
        batch_op.drop_column('peso_fijado')
        batch_op.drop_column('turno')
        batch_op.drop_column('maquina')

    # ### end Alembic commands ###
